name: usf_app
description: "A new Flutter project."
publish_to: 'none'

# Definição de versão
version: 1.0.0+1

# Ambiente SDK
environment:
  sdk: ">=2.18.0 <4.0.0"

# Dependências principais
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  firebase_messaging: ^15.2.0
  introduction_screen: ^3.1.1
  file_picker: ^5.2.0  # Dependência para seleção de arquivos PDF
  flutter_svg: ^1.1.6
  flutter_spinkit: ^5.2.1

# Dependências para testes
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Configuração Flutter
flutter:
  uses-material-design: true
  assets:
    - img/logo_usf.png  # Caminho para a imagem do logo
    - img/logo_usf.svg  # Adicionando o arquivo SVG ao projeto